"use client";

import { useEffect, useState } from "react";

type Project = { id: string; name: string };
type Shot = { prompt: string; modelId: string; duration?: number; resolution?: string; aspectRatio?: string; media?: { assetId: string; role: string }[] };
type Proposal = { id: string; proposal: { title?: string; motionMode?: string; note?: string; shots: Shot[] } };
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}) } }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Request failed"); return body; }

export default function DirectorPage() {
  const [projects, setProjects] = useState<Project[]>([]); const [projectId, setProjectId] = useState(""); const [brief, setBrief] = useState("Create a calm, text-safe five-second product motion shot."); const [proposal, setProposal] = useState<Proposal | null>(null); const [notice, setNotice] = useState("Draft first. Approval is the only path to generation.");
  useEffect(() => { void api<Project[]>("/api/projects").then((list) => { setProjects(list); setProjectId(list[0]?.id || ""); }); }, []);
  const draft = async () => { try { setProposal(await api<Proposal>("/api/director/messages", { method: "POST", body: JSON.stringify({ projectId, prompt: brief }) })); setNotice("Proposal drafted. Review every shot before approval."); } catch (error) { setNotice(error instanceof Error ? error.message : "Draft failed."); } };
  const approve = async () => { if (!proposal) return; try { const result = await api<{ jobs: { id: string }[] }>(`/api/director/proposals/${proposal.id}/approve`, { method: "POST" }); setNotice(`Approved. Created ${result.jobs.length} durable job${result.jobs.length === 1 ? "" : "s"}.`); } catch (error) { setNotice(error instanceof Error ? error.message : "Approval failed."); } };
  return <main className="board"><a href="/">← Studio</a><h1>AI Director</h1><p>The Director drafts an immutable proposal. It cannot submit media independently; approval validates each shot again and queues only that exact version.</p><label>Project<select value={projectId} onChange={(event) => setProjectId(event.target.value)}>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label>Creative brief<textarea value={brief} onChange={(event) => setBrief(event.target.value)} /></label><button className="batch" onClick={draft} disabled={!projectId}>Draft proposal</button><p className="board-notice">{notice}</p>{proposal && <section className="director-card"><h2>{proposal.proposal.title || "Proposed motion plan"}</h2><p>{proposal.proposal.motionMode || "Motion plan"} · {proposal.proposal.note || "Review before approval."}</p><ol>{proposal.proposal.shots.map((shot, index) => <li key={`${proposal.id}-${index}`}><b>Shot {index + 1}</b><span>{shot.prompt}</span><small>{shot.modelId} · {shot.duration ?? "model default"}s · {shot.resolution || "model default"}{shot.aspectRatio ? ` · ${shot.aspectRatio}` : ""}{shot.media?.length ? ` · ${shot.media.map((media) => media.role).join(", ")}` : " · text only"}</small></li>)}</ol><button className="batch" onClick={approve}>Approve this exact proposal and create jobs</button></section>}</main>;
}
