import fs from "node:fs/promises";
import { NextRequest, NextResponse } from "next/server";
import { compositeOverlay, concatenateVideos } from "@/lib/media";
import { saveAsset, toPublicAsset } from "@/lib/assets";
import { store } from "@/lib/store";
import { errorResponse, localOnly } from "@/lib/http";
export const runtime = "nodejs";
export async function POST(request: NextRequest) { const denied = localOnly(request); if (denied) return denied; try { const body = await request.json(); const projectId = String(body.projectId || ""); const videoIds = Array.isArray(body.videoAssetIds) ? body.videoAssetIds : []; const videos = videoIds.map((id: string) => store().getAsset(id)).filter(Boolean); if (!projectId || videos.length !== videoIds.length || videos.some((asset: any) => !asset.mime.startsWith("video/"))) throw new Error("Choose completed local video assets to export."); const output = await concatenateVideos(videos.map((asset: any) => asset.path), body.canvas === "reels" ? "1080:1920" : body.canvas === "feed" ? "1080:1350" : "1080:1440"); let finalPath = output; if (body.overlayAssetId) { const overlay = store().getAsset(String(body.overlayAssetId)); if (!overlay?.mime.startsWith("image/")) throw new Error("Typography overlay must be an image asset."); finalPath = await compositeOverlay(output, overlay.path, body.canvas === "reels" ? "1080:1920" : body.canvas === "feed" ? "1080:1350" : "1080:1440"); }
    const bytes = await fs.readFile(finalPath); const saved = await saveAsset(bytes, "tiny-soho-export.mp4", "video/mp4"); const asset = store().addAsset({ projectId, kind: "export", name: "Tiny Soho export", mime: "video/mp4", path: saved.path, width: null, height: null, duration: null, hash: saved.hash, provenance: JSON.stringify({ source: "ffmpeg", videoAssetIds: videoIds, overlayAssetId: body.overlayAssetId || null }) }); return NextResponse.json(toPublicAsset(asset), { status: 201 }); } catch (error) { return errorResponse(error); } }
