import { NextRequest, NextResponse } from "next/server";
import { configPresent } from "@/lib/config";
import { listModels } from "@/lib/models";
import { store } from "@/lib/store";
import { errorResponse, localOnly } from "@/lib/http";
import { knowledgeConfigured } from "@/lib/knowledge";
export const runtime = "nodejs";
export function GET(request: NextRequest) { const denied = localOnly(request); if (denied) return denied; const db = store(); return NextResponse.json({ configured: configPresent(), creativeKnowledgeConfigured: knowledgeConfigured(), freeQuotaModels: db.getSetting<string[]>("freeQuotaModels") || [], freeQuotaConfirmedAt: db.getSetting<Record<string, string>>("freeQuotaConfirmedAt") || {}, dataDirectory: process.env.TINY_SOHO_DATA_DIR || "~/Library/Application Support/Tiny Soho Studio" }); }
export async function POST(request: NextRequest) { const denied = localOnly(request); if (denied) return denied; try { const body = await request.json(); const candidates: unknown = body.freeQuotaModels; if (!Array.isArray(candidates) || !candidates.every((id): id is string => typeof id === "string")) throw new Error("freeQuotaModels must be a list of model IDs."); const allowed = new Set(listModels().map((model) => model.id)); const selected = [...new Set(candidates)]; if (selected.some((id) => !allowed.has(id))) throw new Error("Unknown model in Free Quota confirmation."); const db = store(); const prior = db.getSetting<Record<string, string>>("freeQuotaConfirmedAt") || {}; const timestamp = new Date().toISOString(); const confirmedAt = Object.fromEntries(selected.map((id) => [id, prior[id] || timestamp])); db.setSetting("freeQuotaModels", selected); db.setSetting("freeQuotaConfirmedAt", confirmedAt); return NextResponse.json({ freeQuotaModels: selected, freeQuotaConfirmedAt: confirmedAt }); } catch (error) { return errorResponse(error); } }
